DROP DATABASE IF EXISTS employee_db;
CREATE DATABASE employee_db;

USE employee_db;

DROP TABLE IF EXISTS department;
CREATE TABLE department (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
dept_Name VARCHAR(40) NOT NULL
);

DROP TABLE IF EXISTS role;
CREATE TABLE role (        
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
title VARCHAR(30),
salary DECIMAL(10, 2),
department_id INT NULL,
FOREIGN KEY (department_id) REFERENCES department(id)
ON DELETE CASCADE
);

DROP TABLE IF EXISTS employee;
CREATE TABLE employee (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INT,
manager_id INT,
FOREIGN KEY (role_id) REFERENCES role(id)
ON DELETE CASCADE,
FOREIGN KEY (manager_id) REFERENCES employee(id)
ON DELETE CASCADE
);